# Generated by Django 2.2.5 on 2020-01-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
