# Generated by Django 2.2.5 on 2020-01-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1_app', '0003_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
